# Site settings
title: mgrachev.com
email: work@mgrachev.com
description: No description
url: http://mgrachev.com # http://localhost:4000
date_format: '%d/%m/%Y'

animated: false
show:
  related_posts: true
  social_icons: true

# Social networks
twitter_username: mgrachev
github_username:  mgrachev
linkedin_username: mgrachev
yandex_money_url:

google_analytics: true
yandex_metrika: true

# Translation
ru:
  updated: Обновлено
  related_posts: Похожие записи
  footer:
    copyright: '&copy; 2014 mgrachev.com'
    theme: Тема
  navigation:
    about: Обо мне
  pagination:
    newer: Новые
    older: Старые

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
sass:
  compressed: true