# Site settings
title: mgrachev.com
author: Михаил Грачев
email: work@mgrachev.com
url: http://mgrachev.com  # http://localhost:4000
date_format: '%d/%m/%Y'

# Options
animated: false
show:
  related_posts: true
  social_icons: true

# Social networks
twitter_username: mgrachev
github_username:  mgrachev
linkedin_username: mgrachev
yandex_money_url:

# Analytics
google_analytics: true
yandex_metrika: true

# Translation
ru:
  updated: Обновлено
  related_posts: Похожие записи
  footer:
    copyright: '&copy; 2014 mgrachev.com'
    available_on: доступен на
    theme: тема
  navigation:
    about: Обо мне
  pagination:
    newer: Новые
    older: Старые
  index:
    coming_soon: Здесь пока ничего нет, но скоро появится :)

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
sass:
  compressed: true