# Site settings
email: work@mgrachev.com
url: http://mgrachev.com
# url: http://localhost:4000
date_format: '%d/%m/%Y'
title: Блог Михаила Грачёва
author: Грачёв Михаил
description: Блог Rails-разработчика

# Options
animated: false
show:
  related_posts: true
  social_icons: true

# Social icons
twitter_username: mgrachev
github_username:  mgrachev
yandex_money_url: https://money.yandex.ru/to/41001477340760
paypal_url: https://www.paypal.me/mgrachev

# Google services
google_analytics: UA-25890313-6
google_verification: zCBCNWNaGsA_SDRTjof3qXR0BqFRST9_R1aQG_xSY3s

# Yandex services
yandex_verification: 58ab8db0550e38f2
yandex_metrika: 26583834

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: mgrachev

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Translation
ru:
  updated: Обновлено
  related_posts: Похожие записи
  footer:
    copyright: '&copy; 2014-2015 Грачёв Михаил'
    available_on: доступен на
    theme: тема
  pagination:
    newer: Новые
    older: Старые
  index:
    coming_soon: Здесь пока ничего нет, но скоро появится :)
  navigation:
    pull_requests: Pull requests
    pull_requests_count: 14
  share_text: 'Поделиться:'

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
sass:
  compressed: true
exclude: [vendor]
gems:
  - jemoji
  - jekyll-sitemap
