# Site settings
title:       Блог Михаила Грачёва
email:       work@mgrachev.com
author:      Грачёв Михаил
description: "Блог Rails-разработчика"
baseurl:     ""
url:         "http://mgrachev.com"
# url:         "http://localhost:4000"
date_format: "%d/%m/%Y"

# Google services
google_analytics: UA-25890313-6
google_verification: zCBCNWNaGsA_SDRTjof3qXR0BqFRST9_R1aQG_xSY3s

# Yandex services
yandex_verification: 58ab8db0550e38f2
yandex_metrika: 26583834

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: mgrachev

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: mgrachev
bitbucket_username:
stackoverflow_id:
twitter_username: mgrachev
skype_username: ifree.
steam_username:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url: "https://www.paypal.me/mgrachev"
flattr_button:
yandex_money_url: "https://money.yandex.ru/to/41001477340760"

# Post sharing icons
show_sharing_icons: true
share_text: 'Поделиться:'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Новые'
    older: 'Старые'
  share_buttons:
    text:         'Поделиться:'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Обновлено'
    minute_read:    'минут прочитано'
    related_posts:  'Похожие записи'
  index:
    coming_soon: 'Здесь пока ничего нет, но скоро появится :)'
  navigation:
    pull_requests:  'Список pull requests на GitHub'
    projects:       'Мои проекты'
    about:          'Обо мне'
    contact:        'Обратная связь'
  footer:
    available_on: 'доступен на'
    theme:        'тема'
  contact:
    email:    'Ваш Email'
    content:  'Что бы вы хотели сказать?'
    subject:  'Обратная связь'
    submit:   'Отправить'
    ajax:
      sending:  'Отправка...'
      sent:     'Сообщение отправлено!'
      error:    'Ошибка!'
  thanks: 'Спасибо что связались со мной. Я отвечу вам как можно скорее.'

counters:
  pull_requests:  38
  projects:       4

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
